### ISSUE TITLE
common files are missing in MiST qsf

### ISSUE THREAD

**Issue by somhi** [gyurco/Atari800XL#3]
atari800_mist.qsf and atari800_SiDi128.qsf does not containg references to modules located in  common folder apart from mist-modules, resulting in a broken compilation.

**Comment by gyurco** [comment]
Sorry, I did not spot this. That's intentional, makeqsf and build.sh script should fill in the missing parts.

**Comment by somhi** [comment]
Thanks for explanation.  I've tested, and it does build project perfectly using ./build.sh
